import type { PipelineEnv } from './types'

export function pipelineEnvFromProcess(): PipelineEnv {
  const e = process.env
  return {
    GITHUB_TOKEN: e.GITHUB_TOKEN,
    HF_TOKEN: e.HF_TOKEN,
    PIPELINE_RSS_FEEDS: e.PIPELINE_RSS_FEEDS,
    PIPELINE_GITHUB_QUERY: e.PIPELINE_GITHUB_QUERY,
    PIPELINE_ARXIV_CATEGORIES: e.PIPELINE_ARXIV_CATEGORIES,
    PIPELINE_NPM_KEYWORDS: e.PIPELINE_NPM_KEYWORDS,
    PIPELINE_ENABLED_SOURCES: e.PIPELINE_ENABLED_SOURCES,
    PIPELINE_USER_AGENT: e.PIPELINE_USER_AGENT,
  }
}
